### Register customer
POST http://localhost:9999/api/customers
Content-Type: application/json

{
    "name": "Kolya",
    "phone": "22",
    "password": "12345678",
    "address": "123 Main St"
}
###

### Token for customer
POST http://localhost:9999/api/customers/token
Content-Type: application/json

{
    "login": "7",
    "password": "12345678"
}
###

### Edit customer
POST http://localhost:9999/api/customers/edit
Authorization: 3ec35f12a304b44dc94d2bb5e5b160bd9c7c6157422c5cfa79ae7fb5b7330a3bd96ba28296a7bdb1b3f516ffccd2ff370cd6afb3f2abd72433fdaeba21249baec6fe11b5cf797395cad76b2bbad96452493323dd6bebedeaa31c2da2b2cf3d027be5d7ed604b4c1327e47eadd4e04a16769bdb89687d10b28cfa45d6ac3f9a7073289b5f005d6e1c8f7a77fe45b3f570e3a9f534da4af5cc9c156d4399fe0d162f1e4008e776f25b48c834a614b57b50b2278747118d0cdf28886f4225771964578148b86b301a036286e55ee7b11c63aac7e2cd6119f14320b8a882d2ebce15cb8c0456b54be287b4ea814ed985eccd0b7308ecf7afab35ce4ce8bbce0fb15b
Content-Type: application/json

{
    "name": "K01ya",
    "password": "12345678",
    "address": "Home"
}
###

### Make admin
POST http://localhost:9999/api/customers/admin
Authorization: defaultAdminsToken
Content-Type: application/json

{
    "id": 7,
    "adminStatus": true
}
###

### Get all customers
GET  http://localhost:9999/api/customers/all
Authorization: defaultAdminsToken
###

### Get customer by id
GET  http://localhost:9999/api/customers/7
Authorization: defaultAdminsToken
###